### ISSUE TITLE
TimeSelector popup appears behind a modal window

### ISSUE THREAD

**Issue by awillerding** [caalador/TimeSelector#10]
I'm using Vaadin V8.06 and created a Modal window with a TimeSelector as one of the fields.  When I click on the time, nothing appears to happen when I expect the TimeSelector window to appear.  When I close the Modal window, the TimeSelector has been rendered behind the Modal window and must be closed separately.

**Comment by bonifacechacha** [comment]
I get the same issue too

**Comment by fmucar** [comment]
same here
It has not been fixed for 3 years now so I assume this is an abandoned project.

**Comment by caalador** [comment]
Sorry for the ages without a fix for a simeple z-index issue.
I never got a mail about new issues and there has been so much going on lately.
