### ISSUE TITLE
z-index position problem when put control in modal window

### ISSUE THREAD

**Issue by jblascojoele** [caalador/TimeSelector#2]
When add the component in a modal window, the clock canvas selection not appears.  When the modal window close, then the canvas appears.

**Comment by caalador** [comment]
I guess the Z-index is lower than the window and it gets hidden in the background.
I'll look into it.

**Comment by jblascojoele** [comment]
I fix the problem in the application that i develope. 
I fixed adding z-index in the next panel class, like other components do in vaadin styles.

.c-TimeSelector-popup {
    background-color: white;
    z-index: 90000;
}
