### ISSUE TITLE
Add-on doesn't work to IE

### ISSUE THREAD

**Issue by rabat22** [caalador/TimeSelector#9]
I have tested your add-on on IE 11 but I have an error with IE.

![image](https://cloud.githubusercontent.com/assets/25502578/23503215/f25b2e02-ff3a-11e6-95ba-9599e2c98cec.png)

When I want select the minute after to select the hour, I have this error and i can't click to Ok to validate.

You can see and test again your add-on to IE. Add-on with Chrome works very good.

**Comment by caalador** [comment]
Sorry that I never reacted to this.
It should not happen that the values that length is used for is null or empty as
long as an empty visibleMinutes array is not set.
Due to IE11 going to EOL in a couple months and me not having time on my hands
at the moment I'll close this as a won't fix.
